"use strict";

// ===========================================================================
// Gerador de casos e captação contínua (modo contínuo): depois dos 15 casos da história, novos pacientes nascem de arquétipos clínicos
// (queixa, história, achados por área, formulação dos 5 Ps, testes e voz) combinados com nome, idade e traços sorteados por uma semente.
// A semente fica no save (state.gen.seeds), então o mesmo paciente volta igual ao recarregar e ao trocar de idioma.
//  · ciclos 2+: a cada 4 semanas nasce uma nova turma (6 a 10 casos, cresce com a Reputação da Clínica);
//  · encaminhamentos: escola, posto, CAPS ou colegas mandam casos pelo celular; a chance sobe com o eixo 🩺 Articulação e com a reputação;
//  · Care.discharge (alta) também pode indicar alguém.
// Estado: state.gen = { seq, seeds: { id: { a, s, n } }, cycles: { ciclo: [ids] }, refs: [{ id, from, week, status, start }] }
// Fórmulas: docs/DESIGN-EVOLUCOES.md, bloco F.
// ===========================================================================
const Gen = (function () {
  const L = window.L;
  const pick = (v) => I18N.pick(v);
  const hash = (s) => String(s).split("").reduce((h, ch) => (h * 31 + ch.charCodeAt(0)) >>> 0, 7);
  function rng(seed) { let a = seed >>> 0; return () => { a = (a + 0x6d2b79f5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
  const st = () => { const g = (state.gen = state.gen || {}); g.seq = g.seq || 0; g.seeds = g.seeds || {}; g.cycles = g.cycles || {}; g.refs = g.refs || []; return g; };
  const week = () => Math.max(1, state.week || 1);
  const fill = (s, o) => String(s).replace(/\{(\w+)\}/g, (m, k) => (o[k] === undefined ? m : o[k]));

  // ---------------------------------------------------------------- nomes e aparência
  const NAMES = { f: ["Ana", "Bruna", "Camila", "Daniela", "Eliane", "Fernanda", "Gisele", "Helga", "Isabela", "Joana", "Karina", "Larissa", "Marta", "Natália", "Olívia", "Paula", "Renata", "Sílvia", "Tatiane", "Vera"], m: ["André", "Bernardo", "Caio", "Diego", "Eduardo", "Fábio", "Gustavo", "Henrique", "Igor", "João", "Kléber", "Leandro", "Márcio", "Nelson", "Otávio", "Paulo", "Ricardo", "Sérgio", "Tomás", "Vítor"] };
  const SURN = ["Alves", "Barbosa", "Cardoso", "Dantas", "Espíndola", "Freitas", "Gomes", "Holanda", "Ibarra", "Jesus", "Klein", "Lopes", "Machado", "Nogueira", "Oliveira", "Pacheco", "Queiroz", "Ramos", "Soares", "Teixeira"];
  const SKINS_ = ["#fbe3d0", "#f6d3b3", "#eab98f", "#d09a6a", "#bf8a5e", "#a8714a", "#7a4b2f", "#5a3a26"], HAIRC = ["#2a1d17", "#6b4630", "#5a3a26", "#a8622a", "#8f8f95", "#e8e6e0"];
  const STY = { f: ["bob", "long", "bun", "curly", "wavy", "ponytail", "braids"], m: ["short", "buzz", "curly", "afro", "pixie"] };
  const TOPS = ["shirt", "sweater", "coat", "plaid", "vest", "wool"];

  // ---------------------------------------------------------------- perfis de teste (z esperado por diagnóstico e bateria)
  const PROF = { tdm: { atencao: -0.9, memoria: -0.7, executivas: -0.9 }, distimia: { atencao: -0.5, executivas: -0.5 }, bipolar2: { executivas: -0.7, atencao: -0.7 }, tag: { atencao: -0.5 }, panico: { atencao: -0.3 }, agorafobia: { atencao: -0.2 }, "sintomas-somaticos": { atencao: -0.2 }, tdah: { atencao: -1.6, memoria: -0.6, executivas: -1.3 }, aprendizagem: { atencao: -0.6, memoria: -1.0, executivas: -0.5 }, luto: { atencao: -0.5 }, adaptacao: { atencao: -0.3 }, tept: { memoria: -0.9, atencao: -1.0 }, "estresse-agudo": { atencao: -0.8 }, "ansiedade-doenca": { atencao: -0.3 } };
  const BATS = ["atencao", "memoria", "executivas", "qi", "emocoes"];

  // ---------------------------------------------------------------- respostas-modelo das consultas 1 e 2 ({s} = o sintoma do arquétipo)
  const INTAKE = [
    { acolhimento: L("Obrigada por ter vindo. Não tem pressa: me conta, com as suas palavras, como {s} tem afetado o seu dia a dia.", "Thank you for coming. There is no rush: tell me, in your own words, how {s} has affected your day to day.", "Gracias por venir. No hay prisa: cuéntame, con tus palabras, cómo {s} ha afectado tu día a día."), tcc: L("Vamos entender {s} passo a passo: quando começa, o que você pensa nessa hora e o que faz em seguida?", "Let's understand {s} step by step: when does it start, what do you think then and what do you do next?", "Entendamos {s} paso a paso: ¿cuándo empieza, qué piensas en ese momento y qué haces después?"), psicodinamica: L("Parece que {s} carrega algo que ainda não teve espaço para ser dito. O que vem primeiro quando você pensa nisso?", "It seems {s} carries something that has not had room to be said yet. What comes first when you think of it?", "Parece que {s} carga algo que aún no tuvo espacio para decirse. ¿Qué viene primero cuando piensas en eso?"), psicoeducacao: L("Antes de tudo: {s} é mais comum do que parece e tem explicação. Posso te contar como isso costuma funcionar?", "First of all: {s} is more common than it seems and has an explanation. Can I tell you how it usually works?", "Antes que nada: {s} es más común de lo que parece y tiene explicación. ¿Puedo contarte cómo suele funcionar?"), comportamental: L("Vamos registrar {s}: quando aparece, quanto dura e o que acontece logo antes e logo depois.", "Let's track {s}: when it shows up, how long it lasts and what happens right before and right after.", "Registremos {s}: cuándo aparece, cuánto dura y qué pasa justo antes y justo después."), diretiva: L("Certo. A partir de amanhã, {s} não pode mais mandar na sua rotina: você faz o que eu combinar e pronto.", "Right. From tomorrow, {s} can no longer rule your routine: you do what we agree and that's it.", "Bien. Desde mañana, {s} ya no puede mandar en tu rutina: haces lo que acordemos y punto.") },
    { acolhimento: L("Isso deve pesar bastante. Fico feliz que tenha contado. Em que momentos do dia é mais difícil?", "That must weigh a lot. I'm glad you told me. At what times of day is it hardest?", "Eso debe pesar mucho. Me alegra que lo hayas contado. ¿En qué momentos del día es más difícil?"), tcc: L("Que ideia passa pela sua cabeça quando isso acontece? Vamos anotar uma delas e ver se ela se sustenta.", "What idea goes through your head when that happens? Let's write one down and see if it holds.", "¿Qué idea pasa por tu cabeza cuando eso ocurre? Anotemos una y veamos si se sostiene."), psicodinamica: L("Isso já apareceu antes na sua vida, de outro jeito? Com quem você se lembra de sentir algo parecido?", "Has this shown up before in your life, in another way? Who do you remember feeling something similar with?", "¿Esto ya apareció antes en tu vida, de otra forma? ¿Con quién recuerdas sentir algo parecido?"), psicoeducacao: L("O que você descreve tem um nome e um caminho de cuidado. Vou te explicar o que se sabe e o que costuma ajudar.", "What you describe has a name and a path of care. I'll explain what is known and what usually helps.", "Lo que describes tiene un nombre y un camino de cuidado. Te explico lo que se sabe y lo que suele ayudar."), comportamental: L("Que atividades você deixou de fazer por causa disso? Vamos escolher uma pequena para retomar esta semana.", "What activities have you stopped because of this? Let's pick a small one to resume this week.", "¿Qué actividades dejaste por esto? Elijamos una pequeña para retomar esta semana."), diretiva: L("Você vai resolver isso sozinha(o): é só se esforçar mais. Cada dia, faça o que tem que fazer, sem desculpa.", "You'll solve this on your own: just try harder. Every day, do what you have to do, no excuses.", "Lo resolverás solo(a): basta esforzarse más. Cada día, haz lo que tienes que hacer, sin excusas.") },
    { acolhimento: L("Obrigada por voltar. Como foi a semana para você, do jeito que ela realmente foi?", "Thank you for coming back. How was the week for you, the way it really was?", "Gracias por volver. ¿Cómo fue la semana para ti, tal como realmente fue?"), tcc: L("Vamos olhar a situação mais difícil da semana: o que aconteceu, o que você pensou, o que sentiu e o que fez.", "Let's look at the hardest situation of the week: what happened, what you thought, felt and did.", "Miremos la situación más difícil de la semana: qué pasó, qué pensaste, sentiste e hiciste."), psicodinamica: L("Reparei que você voltou a esse ponto. O que ele parece guardar para você?", "I noticed you came back to that point. What does it seem to hold for you?", "Noté que volviste a ese punto. ¿Qué parece guardar para ti?"), psicoeducacao: L("Vou mostrar como {s} costuma variar ao longo dos dias, para você saber o que é esperado e o que merece atenção.", "I'll show how {s} usually varies through the days, so you know what to expect and what deserves attention.", "Te muestro cómo suele variar {s} a lo largo de los días, para que sepas qué es esperable y qué merece atención."), comportamental: L("Vamos olhar o seu registro da semana: o que aumentou, o que diminuiu e o que ajudou.", "Let's look at your log for the week: what increased, what decreased and what helped.", "Miremos tu registro de la semana: qué aumentó, qué disminuyó y qué ayudó."), diretiva: L("O combinado era registrar tudo. Quem não registra não melhora. Semana que vem, sem falhas.", "The deal was to record everything. Whoever doesn't record doesn't get better. Next week, no failures.", "Lo acordado era registrarlo todo. Quien no registra no mejora. La semana próxima, sin fallos.") },
    { acolhimento: L("Percebo que já dá para ver melhor o que pesa e o que ajuda. Como você se sente com isso?", "I notice we can now see better what weighs and what helps. How do you feel about that?", "Noto que ya se ve mejor qué pesa y qué ayuda. ¿Cómo te sientes con eso?"), tcc: L("Vamos ligar as pontas: o que você pensa, o que sente e o que faz. Onde dá para mudar o primeiro passo?", "Let's connect the dots: what you think, feel and do. Where can the first step change?", "Unamos los puntos: lo que piensas, sientes y haces. ¿Dónde se puede cambiar el primer paso?"), psicodinamica: L("Há um fio que liga o que você trouxe nas duas consultas. Você o enxerga?", "There is a thread linking what you brought in both sessions. Can you see it?", "Hay un hilo que une lo que trajiste en las dos consultas. ¿Lo ves?"), psicoeducacao: L("Já dá para desenhar o quadro geral do que você vive. Vou explicar em linguagem simples, e você me diz se faz sentido.", "We can now draw the general picture of what you're living. I'll explain in plain language and you tell me if it makes sense.", "Ya se puede dibujar el cuadro general de lo que vives. Te lo explico en lenguaje simple y me dices si tiene sentido."), comportamental: L("Vamos transformar isso em metas pequenas e medíveis para as próximas semanas.", "Let's turn this into small, measurable goals for the coming weeks.", "Convirtamos esto en metas pequeñas y medibles para las próximas semanas."), diretiva: L("Já entendi o suficiente. O plano é este, e o que falta é você cumprir.", "I've understood enough. This is the plan, and what's left is for you to follow it.", "Ya entendí lo suficiente. El plan es este y lo que falta es que lo cumplas.") }
  ];

  // ---------------------------------------------------------------- arquétipos
  const A = {
    depressivo: { answer: "tdm", options: ["tdm", "distimia", "bipolar2", "tag"], age: [24, 58], group: "depressivos", symptom: L("o cansaço e a tristeza", "the tiredness and sadness", "el cansancio y la tristeza"),
      fit: { acolhimento: 4, tcc: 3, comportamental: 3, psicoeducacao: 2, psicodinamica: 2, diretiva: 0 },
      complaint: [L("Cansaço profundo e falta de vontade de fazer as coisas há meses.", "Deep tiredness and no will to do things for months.", "Cansancio profundo y falta de ganas de hacer las cosas desde hace meses."), L("Tristeza que não passa e perda de interesse pelo que gostava.", "Sadness that won't go away and loss of interest in what they liked.", "Tristeza que no pasa y pérdida de interés por lo que le gustaba.")],
      history: [L("Passou por uma mudança grande no último ano e diz que 'nada mais tem graça'. A família nota o isolamento.", "Went through a big change last year and says 'nothing is fun anymore'. The family notices the withdrawal.", "Pasó por un gran cambio el último año y dice que 'nada tiene gracia'. La familia nota el aislamiento."), L("Trabalha, mas em ritmo lento; dorme mal e come pouco. Procurou ajuda por insistência de alguém próximo.", "Works, but slowly; sleeps badly and eats little. Sought help at a loved one's insistence.", "Trabaja, pero despacio; duerme mal y come poco. Buscó ayuda por insistencia de alguien cercano.")],
      steps: [L("(voz baixa) 'Não sei bem por que vim... tá tudo pesado, sabe? Nada mais tem graça.'", "(low voice) 'I don't really know why I came... everything feels heavy, you know? Nothing is fun anymore.'", "(voz baja) 'No sé bien por qué vine... todo pesa, ¿sabes? Nada tiene gracia.'"), L("'Acordo cansada(o) e o dia todo é assim. Faço o básico e só.'", "'I wake up tired and the whole day is like that. I do the basics and that's it.'", "'Me despierto cansada(o) y todo el día es así. Hago lo básico y ya.'"), L("'Essa semana foi parecida. Tive um dia um pouco melhor, mas passou rápido.'", "'This week was similar. I had one slightly better day, but it passed quickly.'", "'Esta semana fue parecida. Tuve un día un poco mejor, pero pasó rápido.'"), L("'Comecei a perceber o que piora e o que ajuda. Ainda é difícil, mas dá pra ver.'", "'I started to notice what makes it worse and what helps. It's still hard, but I can see it.'", "'Empecé a notar qué empeora y qué ayuda. Aún es difícil, pero se ve.'")],
      note: L("Humor rebaixado e perda de prazer.", "Low mood and loss of pleasure.", "Ánimo bajo y pérdida de placer."),
      find: { humor: [L("Humor deprimido e perda de prazer quase todo dia, há meses.", "Depressed mood and loss of pleasure almost daily for months.", "Ánimo deprimido y pérdida de placer casi a diario desde hace meses."), L("Nada mais tem graça... é quase todo dia, faz meses. Eu me sinto sem energia pra nada.", "Nothing is fun anymore... it's almost every day, for months. I have no energy for anything.", "Nada tiene gracia ya... es casi todos los días, hace meses. No tengo energía para nada."), { tdm: 3, distimia: 1, bipolar2: 0, tag: -1 }], sono: [L("Dorme mal, acorda cedo e sente cansaço o dia todo.", "Sleeps badly, wakes early and feels tired all day.", "Duerme mal, se despierta temprano y se siente cansada(o) todo el día."), L("Durmo mal, acordo cedo e o cansaço fica o dia inteiro.", "I sleep badly, wake up early and the tiredness stays all day.", "Duermo mal, me despierto temprano y el cansancio se queda todo el día."), { tdm: 2, distimia: 1 }], corpo: [L("Perdeu apetite e alguns quilos sem querer.", "Lost appetite and a few kilos unintentionally.", "Perdió el apetito y unos kilos sin querer."), L("Perdi o apetite e emagreci sem querer.", "I lost my appetite and lost weight without trying.", "Perdí el apetito y adelgacé sin querer."), { tdm: 2, distimia: 0 }], inicio: [L("Começou há alguns meses e piorou aos poucos, sem fases de euforia.", "Started a few months ago and worsened gradually, with no euphoric phases.", "Empezó hace unos meses y empeoró poco a poco, sin fases de euforia."), L("Começou faz uns meses e foi piorando. Euforia, nunca tive.", "It started a few months ago and kept getting worse. Euphoria, never.", "Empezó hace unos meses y fue empeorando. Euforia, nunca tuve."), { tdm: 2, distimia: -1, bipolar2: -2 }], func: [L("Trabalha com muito esforço e evita convites.", "Works with great effort and avoids invitations.", "Trabaja con mucho esfuerzo y evita las invitaciones."), L("Trabalho com muito esforço e recuso os convites. Não tenho ânimo.", "I work with great effort and turn down invitations. I have no drive.", "Trabajo con mucho esfuerzo y rechazo las invitaciones. No tengo ánimo."), { tdm: 2, distimia: 1 }]},
      form: { predisposing: L("Sensibilidade a perdas e autoexigência alta.", "Sensitivity to losses and high self-demand.", "Sensibilidad a las pérdidas y autoexigencia alta."), precipitating: L("Uma mudança importante no último ano.", "An important change in the past year.", "Un cambio importante en el último año."), perpetuating: L("Isolamento, pouca atividade e sono ruim.", "Withdrawal, little activity and poor sleep.", "Aislamiento, poca actividad y mal sueño."), protective: L("Família presente e busca de ajuda.", "Present family and help-seeking.", "Familia presente y búsqueda de ayuda.") },
      why: L("Humor deprimido, perda de prazer, alteração do sono e do apetite por meses, sem fases de euforia, sustentam o transtorno depressivo maior. A distimia seria mais crônica e leve.", "Depressed mood, loss of pleasure, sleep and appetite changes for months, with no euphoric phases, support major depressive disorder. Dysthymia would be more chronic and milder.", "Ánimo deprimido, pérdida de placer, alteración del sueño y del apetito por meses, sin fases de euforia, sustentan el trastorno depresivo mayor. La distimia sería más crónica y leve."),
      voice: { pre: [L("Ah...", "Ah...", "Ah..."), L("É que...", "It's just that...", "Es que...")], post: L("Desculpa.", "Sorry.", "Perdón."), ref: [L("A semana foi de cama e tela.", "The week was bed and screens.", "La semana fue de cama y pantalla."), L("Saí de casa duas vezes, mas cansou.", "I left home twice, but it was tiring.", "Salí de casa dos veces, pero cansó."), L("Encontrei uma pessoa querida e ri de verdade.", "I met a dear person and really laughed.", "Me encontré con alguien querido y me reí de verdad.")], hookA: L("Como foram as suas manhãs?", "What have your mornings been like?", "¿Cómo han sido tus mañanas?"), hookB: L("Que pequena atividade dá pra retomar esta semana?", "What small activity could you resume this week?", "¿Qué pequeña actividad se puede retomar esta semana?") } },
    ansioso: { answer: "tag", options: ["tag", "panico", "tdah", "tdm"], age: [22, 55], group: "ansiedade", symptom: L("as preocupações", "the worries", "las preocupaciones"),
      fit: { acolhimento: 3, tcc: 4, comportamental: 3, psicoeducacao: 3, psicodinamica: 2, diretiva: 0 },
      complaint: [L("Preocupação constante com tudo e dificuldade de relaxar.", "Constant worry about everything and trouble relaxing.", "Preocupación constante por todo y dificultad para relajarse."), L("Tensão no corpo e cabeça que não desliga.", "Body tension and a mind that won't switch off.", "Tensión en el cuerpo y una cabeza que no se apaga.")],
      history: [L("Sempre foi 'preocupada(o)', mas há mais de seis meses piorou. Vive antecipando problemas e dorme mal.", "Has always been a 'worrier', but for over six months it has worsened. Keeps anticipating problems and sleeps badly.", "Siempre fue 'preocupada(o)', pero hace más de seis meses empeoró. Vive anticipando problemas y duerme mal."), L("Cobra-se muito no trabalho e na família; sente o corpo tenso o dia todo.", "Demands a lot of themselves at work and at home; feels tense all day.", "Se exige mucho en el trabajo y en la familia; siente el cuerpo tenso todo el día.")],
      steps: [L("'Eu me preocupo com tudo, sabe? Não consigo desligar. Já tentei relaxar e não adianta.'", "'I worry about everything, you know? I can't switch off. I've tried relaxing and it doesn't help.'", "'Me preocupo por todo, ¿sabes? No logro desconectar. Ya intenté relajarme y no sirve.'"), L("'À noite piora: fico repassando o que pode dar errado amanhã.'", "'At night it gets worse: I keep going over what could go wrong tomorrow.'", "'De noche empeora: me quedo repasando lo que puede salir mal mañana.'"), L("'Essa semana tive uns dias tensos, mas percebi que muita coisa nem aconteceu.'", "'This week I had some tense days, but I noticed a lot of it never happened.'", "'Esta semana tuve unos días tensos, pero noté que mucho ni ocurrió.'"), L("'Já consigo notar quando o pensamento começa a rodar. Ainda é difícil parar.'", "'I can now notice when the thought starts spinning. It's still hard to stop.'", "'Ya noto cuando el pensamiento empieza a dar vueltas. Aún cuesta parar.'")],
      note: L("Preocupação excessiva e difícil de controlar.", "Excessive worry that is hard to control.", "Preocupación excesiva y difícil de controlar."),
      find: { ansiedade: [L("Preocupação excessiva com várias áreas, por mais de seis meses.", "Excessive worry about several areas for over six months.", "Preocupación excesiva por varias áreas durante más de seis meses."), L("Me preocupo com trabalho, dinheiro, família, tudo. Faz mais de seis meses.", "I worry about work, money, family, everything. It's been over six months.", "Me preocupo por trabajo, dinero, familia, todo. Hace más de seis meses."), { tag: 3, panico: 0, tdah: 0, tdm: 0 }], corpo: [L("Tensão muscular, dor de cabeça e cansaço.", "Muscle tension, headaches and fatigue.", "Tensión muscular, dolor de cabeza y cansancio."), L("Meus ombros vivem duros, tenho dor de cabeça e me canso fácil.", "My shoulders are always stiff, I get headaches and tire easily.", "Mis hombros están siempre duros, tengo dolor de cabeza y me canso fácil."), { tag: 2, panico: 0 }], sono: [L("Demora a dormir por pensamentos repetitivos.", "Slow to fall asleep because of repetitive thoughts.", "Tarda en dormirse por pensamientos repetitivos."), L("Demoro a dormir, a cabeça fica repassando tudo.", "I take long to fall asleep, my head keeps going over everything.", "Tardo en dormirme, la cabeza repasa todo."), { tag: 2, tdm: 1 }], func: [L("Rende, mas com muito custo e autocobrança.", "Performs, but at great cost and self-pressure.", "Rinde, pero con mucho costo y autoexigencia."), L("Eu entrego, mas me cobro demais e chego exausta(o).", "I deliver, but I demand too much of myself and arrive exhausted.", "Cumplo, pero me exijo demasiado y llego agotada(o)."), { tag: 2, tdah: 0 }], inicio: [L("O padrão vem de anos e piorou nos últimos seis meses, sem crises súbitas.", "The pattern goes back years and worsened in the last six months, with no sudden attacks.", "El patrón viene de años y empeoró en los últimos seis meses, sin crisis súbitas."), L("Sempre fui assim, mas piorou este ano. Crise do nada, isso não tenho.", "I've always been like this, but it got worse this year. Sudden attacks, I don't have.", "Siempre fui así, pero empeoró este año. Crisis de la nada, no tengo."), { tag: 2, panico: -2 }]},
      form: { predisposing: L("Temperamento ansioso e perfeccionismo.", "Anxious temperament and perfectionism.", "Temperamento ansioso y perfeccionismo."), precipitating: L("Aumento de cobranças no trabalho.", "More demands at work.", "Más exigencias en el trabajo."), perpetuating: L("Antecipação de problemas e pouca pausa.", "Anticipating problems and few breaks.", "Anticipar problemas y pocas pausas."), protective: L("Rede de amigos e disposição para tratar.", "Friend network and willingness to treat.", "Red de amigos y disposición a tratarse.") },
      why: L("Preocupação excessiva e difícil de controlar, por mais de seis meses, com tensão, sono ruim e prejuízo, sustenta o transtorno de ansiedade generalizada. Não há crises súbitas de pânico.", "Excessive, hard-to-control worry for over six months, with tension, poor sleep and impairment, supports generalized anxiety disorder. There are no sudden panic attacks.", "La preocupación excesiva y difícil de controlar, por más de seis meses, con tensión, mal sueño y perjuicio, sustenta el trastorno de ansiedad generalizada. No hay crisis súbitas de pánico."),
      voice: { pre: [L("E se...", "What if...", "¿Y si..."), L("Então...", "So...", "Entonces...")], post: L("Será que é normal?", "Is that normal?", "¿Será normal?"), ref: [L("Passei a semana ensaiando problemas que nem vieram.", "I spent the week rehearsing problems that never came.", "Pasé la semana ensayando problemas que no llegaron."), L("Respirei em duas situações e ajudou um pouco.", "I breathed in two situations and it helped a little.", "Respiré en dos situaciones y ayudó un poco."), L("Notei a preocupação vindo e deixei passar.", "I noticed the worry coming and let it pass.", "Noté la preocupación venir y la dejé pasar.")], hookA: L("Em que parte do corpo você sente a preocupação?", "Where in your body do you feel the worry?", "¿En qué parte del cuerpo sientes la preocupación?"), hookB: L("Vamos separar o que dá para resolver do que só dá para aceitar?", "Shall we separate what can be solved from what can only be accepted?", "¿Separamos lo que se puede resolver de lo que solo se puede aceptar?") } },
    panico: { answer: "panico", options: ["panico", "tag", "agorafobia", "sintomas-somaticos"], age: [21, 50], group: "ansiedade", symptom: L("as crises de pânico", "the panic attacks", "las crisis de pánico"),
      fit: { acolhimento: 3, tcc: 4, comportamental: 3, psicoeducacao: 4, psicodinamica: 1, diretiva: 0 },
      complaint: [L("Crises súbitas de falta de ar e coração disparado, com medo de morrer.", "Sudden attacks of breathlessness and racing heart, with fear of dying.", "Crisis súbitas de falta de aire y corazón disparado, con miedo a morir."), L("Medo de ter outra crise em qualquer lugar.", "Fear of having another attack anywhere.", "Miedo a tener otra crisis en cualquier lugar.")],
      history: [L("A primeira crise foi há poucos meses, sem motivo claro; os exames deram normais. Passou a evitar lugares cheios.", "The first attack was a few months ago, for no clear reason; tests came back normal. Started avoiding crowded places.", "La primera crisis fue hace pocos meses, sin motivo claro; los exámenes salieron normales. Empezó a evitar lugares llenos."), L("Toma muito café e dorme pouco. Procurou o pronto-socorro duas vezes.", "Drinks a lot of coffee and sleeps little. Went to the ER twice.", "Toma mucho café y duerme poco. Fue a urgencias dos veces.")],
      steps: [L("'Do nada meu coração dispara, falta ar, eu acho que vou morrer. Já fui ao pronto-socorro e não deu nada.'", "'Out of nowhere my heart races, I can't breathe, I think I'm going to die. I went to the ER and nothing came up.'", "'De la nada mi corazón se dispara, me falta el aire, creo que me voy a morir. Fui a urgencias y no salió nada.'"), L("'Agora vivo com medo da próxima. Evito lugar fechado, evito sair sozinho(a).'", "'Now I live afraid of the next one. I avoid closed places, avoid going out alone.'", "'Ahora vivo con miedo de la próxima. Evito lugares cerrados, evito salir solo(a).'"), L("'Tive uma crise menor. Lembrei da respiração e passou mais rápido.'", "'I had a smaller attack. I remembered the breathing and it passed faster.'", "'Tuve una crisis menor. Recordé la respiración y pasó más rápido.'"), L("'Já consigo ficar mais tempo na rua. O medo vem, mas eu fico.'", "'I can stay out longer now. The fear comes, but I stay.'", "'Ya puedo estar más tiempo en la calle. El miedo viene, pero me quedo.'")],
      note: L("Crise súbita com medo de morrer; exames normais.", "Sudden attack with fear of dying; normal tests.", "Crisis súbita con miedo a morir; exámenes normales."),
      find: { corpo: [L("Coração disparado, falta de ar e tremor em picos de minutos.", "Racing heart, breathlessness and tremor in peaks of minutes.", "Corazón disparado, falta de aire y temblor en picos de minutos."), L("Coração disparado, falta de ar, tremor... tudo em poucos minutos.", "Racing heart, breathlessness, tremor... all within a few minutes.", "Corazón disparado, falta de aire, temblor... todo en pocos minutos."), { panico: 3, tag: 0, agorafobia: 1, "sintomas-somaticos": 1 }], ansiedade: [L("Medo de nova crise e de suas consequências.", "Fear of another attack and its consequences.", "Miedo a otra crisis y sus consecuencias."), L("Vivo com medo da próxima crise, mais do que da crise em si.", "I live afraid of the next attack, more than the attack itself.", "Vivo con miedo de la próxima crisis, más que de la crisis en sí."), { panico: 3, tag: -1 }], func: [L("Evita metrô, reuniões e lugares cheios.", "Avoids the subway, meetings and crowded places.", "Evita el metro, las reuniones y lugares llenos."), L("Parei de pegar metrô e evito reuniões e lugares cheios.", "I stopped taking the subway and avoid meetings and crowded places.", "Dejé de tomar el metro y evito reuniones y lugares llenos."), { panico: 2, agorafobia: 2 }], inicio: [L("Primeira crise há poucos meses, sem gatilho claro.", "First attack a few months ago, with no clear trigger.", "Primera crisis hace pocos meses, sin desencadenante claro."), L("A primeira foi há uns meses, do nada, sem motivo nenhum.", "The first was a few months ago, out of nowhere, for no reason.", "La primera fue hace unos meses, de la nada, sin motivo."), { panico: 2, tag: -1 }], subst: [L("Muito café e energético; reduzir ajudou um pouco.", "Lots of coffee and energy drinks; cutting back helped a little.", "Mucho café y bebidas energéticas; reducir ayudó un poco."), L("Eu tomava muito café e energético; diminuí e melhorou um pouco.", "I used to drink lots of coffee and energy drinks; I cut back and it improved a bit.", "Tomaba mucho café y bebidas energéticas; reduje y mejoró un poco."), { panico: 1 }]},
      form: { predisposing: L("Sensibilidade às sensações do corpo.", "Sensitivity to body sensations.", "Sensibilidad a las sensaciones del cuerpo."), precipitating: L("Período de estresse e pouco sono.", "A stressful period with little sleep.", "Un período de estrés y poco sueño."), perpetuating: L("Medo da próxima crise, evitação e cafeína.", "Fear of the next attack, avoidance and caffeine.", "Miedo a la próxima crisis, evitación y cafeína."), protective: L("Exames normais e apoio da família.", "Normal tests and family support.", "Exámenes normales y apoyo de la familia.") },
      why: L("Crises súbitas e inesperadas com sintomas físicos intensos, medo de novas crises e evitação sustentam o transtorno de pânico. A ansiedade generalizada é difusa, sem picos de minutos.", "Sudden, unexpected attacks with intense physical symptoms, fear of new attacks and avoidance support panic disorder. Generalized anxiety is diffuse, with no peaks of minutes.", "Crisis súbitas e inesperadas con síntomas físicos intensos, miedo a nuevas crisis y evitación sustentan el trastorno de pánico. La ansiedad generalizada es difusa, sin picos de minutos."),
      voice: { pre: [L("Olha,", "Look,", "Mira,"), L("Tecnicamente...", "Technically...", "Técnicamente...")], post: L("Faz sentido?", "Does that make sense?", "¿Tiene sentido?"), ref: [L("Tive duas crises e saí correndo de um lugar.", "I had two attacks and ran out of a place.", "Tuve dos crisis y salí corriendo de un lugar."), L("Fiquei na fila do mercado, senti o coração acelerar e esperei.", "I stayed in the supermarket line, felt my heart race and waited.", "Me quedé en la fila del mercado, sentí el corazón acelerar y esperé."), L("Fui de metrô até o trabalho. Passou sozinho.", "I took the subway to work. It passed on its own.", "Fui en metro al trabajo. Pasó solo.")], hookA: L("O que você diz para si quando o coração acelera?", "What do you tell yourself when your heart races?", "¿Qué te dices cuando el corazón se acelera?"), hookB: L("Vamos praticar a respiração e uma exposição pequena?", "Shall we practice breathing and a small exposure?", "¿Practicamos la respiración y una exposición pequeña?") } },
    tdah: { answer: "tdah", options: ["tdah", "tag", "tdm", "aprendizagem"], age: [22, 45], group: "neuro", symptom: L("a desatenção", "the inattention", "la desatención"),
      fit: { acolhimento: 3, tcc: 3, comportamental: 4, psicoeducacao: 4, psicodinamica: 1, diretiva: 1 },
      complaint: [L("Dificuldade de manter o foco, esquecimentos e atrasos constantes.", "Trouble keeping focus, constant forgetfulness and lateness.", "Dificultad para mantener el foco, olvidos y retrasos constantes."), L("Começa muita coisa e não termina; vida bagunçada.", "Starts many things and doesn't finish; a messy life.", "Empieza muchas cosas y no termina; vida desordenada.")],
      history: [L("Desde a escola era 'da lua'. Hoje perde prazos no trabalho e esquece compromissos, e isso vem gerando conflitos.", "Since school was 'in the clouds'. Now misses deadlines at work and forgets appointments, causing conflicts.", "Desde la escuela era 'distraída(o)'. Hoy pierde plazos en el trabajo y olvida compromisos, y eso genera conflictos."), L("Muda de projeto o tempo todo e se sente inquieta(o) por dentro.", "Changes projects all the time and feels restless inside.", "Cambia de proyecto todo el tiempo y se siente inquieta(o) por dentro.")],
      steps: [L("'Eu esqueço tudo, perco prazo, começo mil coisas e não termino. Meu chefe já perdeu a paciência.'", "'I forget everything, miss deadlines, start a thousand things and finish none. My boss has lost patience.'", "'Olvido todo, pierdo plazos, empiezo mil cosas y no termino ninguna. Mi jefe ya perdió la paciencia.'"), L("'Sempre foi assim, desde criança. Eu me distraio fácil, mas quando o assunto me interessa, eu vou longe.'", "'It's always been like this, since childhood. I get distracted easily, but when something interests me I go far.'", "'Siempre fue así, desde niña(o). Me distraigo fácil, pero cuando el tema me interesa llego lejos.'"), L("'Essa semana usei o alarme e a lista. Esqueci só metade das coisas.'", "'This week I used the alarm and the list. I only forgot half the things.'", "'Esta semana usé la alarma y la lista. Olvidé solo la mitad de las cosas.'"), L("'Organizei a agenda e cumpri um prazo. Estranho, mas bom.'", "'I organized my calendar and met a deadline. Strange, but good.'", "'Organicé la agenda y cumplí un plazo. Raro, pero bueno.'")],
      note: L("Desatenção desde a infância, em vários ambientes.", "Inattention since childhood, in several settings.", "Desatención desde la infancia, en varios ambientes."),
      find: { func: [L("Perde prazos e esquece compromissos, no trabalho e em casa.", "Misses deadlines and forgets commitments, at work and at home.", "Pierde plazos y olvida compromisos, en el trabajo y en casa."), L("Perco prazo, esqueço compromisso, no trabalho e em casa.", "I miss deadlines, forget commitments, at work and at home.", "Pierdo plazos, olvido compromisos, en el trabajo y en casa."), { tdah: 3, tag: 0, tdm: 1, aprendizagem: 0 }], inicio: [L("Sinais desde a infância, antes dos 12 anos.", "Signs since childhood, before age 12.", "Señales desde la infancia, antes de los 12 años."), L("Sempre fui assim, desde criança, muito antes dos 12 anos.", "I've always been like this, since childhood, well before age 12.", "Siempre fui así, desde niña(o), mucho antes de los 12 años."), { tdah: 3, tdm: -2, tag: -1 }], pensamento: [L("Foca bem no que interessa e se perde no monótono.", "Focuses well on what interests and gets lost in the monotonous.", "Se concentra bien en lo que interesa y se pierde en lo monótono."), L("Em coisa que me interessa eu me concentro horas; no monótono eu me perco.", "On things that interest me I focus for hours; on the monotonous I get lost.", "En lo que me interesa me concentro horas; en lo monótono me pierdo."), { tdah: 2, aprendizagem: -1 }], corpo: [L("Inquietação, interrompe e mexe as pernas.", "Restlessness, interrupts and fidgets.", "Inquietud, interrumpe y mueve las piernas."), L("Não consigo ficar parada(o), mexo as pernas e interrompo sem perceber.", "I can't sit still, I fidget and interrupt without noticing.", "No consigo quedarme quieta(o), muevo las piernas e interrumpo sin darme cuenta."), { tdah: 2 }], humor: [L("Frustração por falhas, mas sem tristeza persistente.", "Frustration with failures, but no persistent sadness.", "Frustración por los fallos, pero sin tristeza persistente."), L("Me frustro com os erros, mas triste o tempo todo, não.", "I get frustrated with mistakes, but sad all the time, no.", "Me frustro con los errores, pero triste todo el tiempo, no."), { tdah: 1, tdm: -2 }]},
      form: { predisposing: L("Temperamento agitado e histórico familiar de distração.", "A restless temperament and family history of distractibility.", "Temperamento inquieto y antecedentes familiares de distracción."), precipitating: L("Aumento de responsabilidades no trabalho.", "More responsibilities at work.", "Más responsabilidades en el trabajo."), perpetuating: L("Falta de rotina e ambientes cheios de estímulo.", "Lack of routine and stimulus-filled settings.", "Falta de rutina y ambientes llenos de estímulos."), protective: L("Criatividade e interesse por novidades.", "Creativity and interest in novelty.", "Creatividad e interés por las novedades.") },
      why: L("Desatenção e inquietação desde a infância, em vários ambientes, com prejuízo atual e sem tristeza persistente, sustentam o TDAH. A ansiedade não explica o início precoce.", "Inattention and restlessness since childhood, in several settings, with current impairment and no persistent sadness, support ADHD. Anxiety does not explain the early onset.", "Desatención e inquietud desde la infancia, en varios ambientes, con perjuicio actual y sin tristeza persistente, sustentan el TDAH. La ansiedad no explica el inicio temprano."),
      voice: { pre: [L("Peraí, o que eu ia dizer?", "Wait, what was I going to say?", "Espera, ¿qué iba a decir?"), L("Ah, lembrei!", "Oh, I remembered!", "¡Ah, me acordé!")], post: L("Já falei isso, né?", "I already said that, right?", "Ya dije eso, ¿no?"), ref: [L("Esqueci a reunião e cheguei com trinta minutos de atraso.", "I forgot the meeting and arrived thirty minutes late.", "Olvidé la reunión y llegué con treinta minutos de retraso."), L("Usei a lista e cumpri metade.", "I used the list and got half done.", "Usé la lista y cumplí la mitad."), L("Cumpri o prazo com a agenda.", "I met the deadline with the calendar.", "Cumplí el plazo con la agenda.")], hookA: L("O que você sente quando perde um prazo?", "What do you feel when you miss a deadline?", "¿Qué sientes cuando pierdes un plazo?"), hookB: L("Vamos montar um sistema de alarmes e lista visual?", "Shall we set up an alarm system and a visual list?", "¿Armamos un sistema de alarmas y una lista visual?") } },
    luto: { answer: "luto", options: ["luto", "tdm", "adaptacao", "tag"], age: [34, 68], group: "trauma", symptom: L("a saudade e o vazio", "the longing and emptiness", "la añoranza y el vacío"),
      fit: { acolhimento: 4, tcc: 2, comportamental: 2, psicoeducacao: 3, psicodinamica: 3, diretiva: 0 },
      complaint: [L("Não consegue voltar à vida desde a perda de alguém muito querido.", "Cannot get back to life since losing someone very dear.", "No logra volver a la vida desde la pérdida de alguien muy querido."), L("Saudade intensa e vazio que não diminuem com o tempo.", "Intense longing and emptiness that don't ease with time.", "Añoranza intensa y vacío que no disminuyen con el tiempo.")],
      history: [L("Perdeu alguém próximo há mais de um ano. Evita lugares que lembram a pessoa e sente pressão para 'superar'.", "Lost someone close over a year ago. Avoids places that remind of them and feels pressure to 'get over it'.", "Perdió a alguien cercano hace más de un año. Evita lugares que la recuerdan y siente presión por 'superarlo'."), L("Mantém a casa, mas sem prazer; afastou-se dos amigos.", "Keeps up the house but without pleasure; withdrew from friends.", "Mantiene la casa, pero sin placer; se alejó de los amigos.")],
      steps: [L("'Já faz mais de um ano e todo mundo diz que eu devia estar melhor. Mas a casa ficou tão quieta...'", "'It's been over a year and everyone says I should be better. But the house got so quiet...'", "'Ya pasó más de un año y todos dicen que ya debería estar mejor. Pero la casa quedó tan callada...'"), L("'Não consigo ir onde a gente ia junto. Prefiro ficar em casa.'", "'I can't go where we used to go together. I prefer staying home.'", "'No puedo ir donde íbamos juntos. Prefiero quedarme en casa.'"), L("'Essa semana olhei umas fotos e chorei, mas foi um choro que aliviou.'", "'This week I looked at some photos and cried, but it was a crying that relieved.'", "'Esta semana miré unas fotos y lloré, pero fue un llanto que alivió.'"), L("'Fui à missa de novo. Doeu, mas me senti perto dele(a).'", "'I went to church again. It hurt, but I felt close to them.'", "'Fui otra vez a misa. Dolió, pero me sentí cerca de él/ella.'")],
      note: L("Luto prolongado; pressão para 'superar'.", "Prolonged grief; pressure to 'get over it'.", "Duelo prolongado; presión por 'superarlo'."),
      find: { humor: [L("Saudade intensa e vazio quase todo dia desde a perda.", "Intense longing and emptiness almost every day since the loss.", "Añoranza intensa y vacío casi a diario desde la pérdida."), L("A saudade vem toda hora. É como se tivesse um buraco onde a pessoa ficava.", "The longing comes all the time. It's like there's a hole where the person used to be.", "La añoranza viene a todas horas. Es como si hubiera un hueco donde estaba la persona."), { luto: 3, tdm: 2, adaptacao: 0, tag: -1 }], sono: [L("Acorda de madrugada procurando a pessoa.", "Wakes at dawn looking for the person.", "Se despierta de madrugada buscando a la persona."), L("Acordo de madrugada e estico o braço pro lado da cama... aí lembro.", "I wake at dawn and reach for the other side of the bed... then I remember.", "Me despierto de madrugada y estiro el brazo hacia el otro lado de la cama... y entonces recuerdo."), { luto: 2, tdm: 1 }], social: [L("Afastou-se de amigos e evita lugares ligados à pessoa.", "Withdrew from friends and avoids places tied to the person.", "Se alejó de amigos y evita lugares ligados a la persona."), L("Não consigo ir aos lugares de antes. Prefiro ficar em casa.", "I can't go to the old places. I prefer staying home.", "No puedo ir a los lugares de antes. Prefiero quedarme en casa."), { luto: 2, tdm: 1, adaptacao: -1 }], inicio: [L("Tudo começou com a perda, há mais de um ano, sem melhora.", "It all began with the loss over a year ago, without improvement.", "Todo empezó con la pérdida hace más de un año, sin mejoría."), L("Foi quando a pessoa morreu. Mais de um ano e não passa.", "It was when the person died. Over a year and it doesn't pass.", "Fue cuando murió la persona. Más de un año y no pasa."), { luto: 3, tdm: 1, adaptacao: -1 }], func: [L("Cuida da casa sem prazer e deixou de cozinhar para si.", "Keeps up the house without pleasure and stopped cooking for themselves.", "Mantiene la casa sin placer y dejó de cocinar para sí."), L("Faço o essencial. Cozinhar pra uma pessoa só não tem graça.", "I do the essentials. Cooking for one person is no fun.", "Hago lo esencial. Cocinar para una sola persona no tiene gracia."), { luto: 1, tdm: 2 }]},
      form: { predisposing: L("Vínculo muito forte e dependente com quem se foi.", "A very strong, dependent bond with the person who is gone.", "Un vínculo muy fuerte y dependiente con quien se fue."), precipitating: L("A morte de alguém muito querido.", "The death of someone very dear.", "La muerte de alguien muy querido."), perpetuating: L("Isolamento e cobrança para 'superar'.", "Isolation and pressure to 'get over it'.", "Aislamiento y presión por 'superarlo'."), protective: L("Fé, família e memória afetiva.", "Faith, family and loving memory.", "Fe, familia y memoria afectiva.") },
      why: L("Saudade intensa e persistente por mais de doze meses, com vazio, evitação e prejuízo, sustenta o luto prolongado. O humor rebaixado está ligado à perda, e não a um episódio depressivo independente.", "Intense, persistent longing for over twelve months, with emptiness, avoidance and impairment, supports prolonged grief. The low mood is tied to the loss, not to an independent depressive episode.", "La añoranza intensa y persistente por más de doce meses, con vacío, evitación y perjuicio, sustenta el duelo prolongado. El ánimo bajo se liga a la pérdida y no a un episodio depresivo independiente."),
      voice: { pre: [L("(suspira)", "(sighs)", "(suspira)"), L("Sabe...", "You know...", "Sabes...")], post: L("Desculpa, me estendi.", "Sorry, I went on.", "Perdón, me extendí."), ref: [L("Fiquei a semana em casa, olhando para o telefone.", "I spent the week at home, looking at the phone.", "Pasé la semana en casa, mirando el teléfono."), L("Fui a um lugar que a gente gostava e aguentei um tempo.", "I went to a place we loved and lasted a while.", "Fui a un lugar que nos gustaba y aguanté un rato."), L("Falei da pessoa com uma amiga e sorri lembrando.", "I talked about the person with a friend and smiled remembering.", "Hablé de la persona con una amiga y sonreí recordando.")], hookA: L("O que você mais sente falta, no dia a dia?", "What do you miss most, day to day?", "¿Qué extrañas más, en el día a día?"), hookB: L("Vamos pensar num pequeno ritual de lembrança?", "Shall we think of a small remembrance ritual?", "¿Pensamos en un pequeño ritual de recuerdo?") } }
,
    // ESGOTAMENTO NO TRABALHO (7.5) — o perfil que só chega quando a clínica tem nome.
    // Burnout não é diagnóstico do Manual: é um fenômeno ligado ao trabalho. O que se fecha aqui é
    // TRANSTORNO DE ADAPTAÇÃO, e o diferencial contra depressão é justamente o ensino do caso — o
    // humor levanta na folga, o que não acontece num episódio depressivo.
    esgotamento: { answer: "adaptacao", options: ["adaptacao", "tdm", "distimia", "insonia"], age: [26, 52], group: "depressivos", symptom: L("o esgotamento com o trabalho", "the exhaustion with work", "el agotamiento con el trabajo"),
      fit: { acolhimento: 3, tcc: 3, comportamental: 2, psicoeducacao: 4, psicodinamica: 2, diretiva: 1 },
      complaint: [L("Esgotamento com o trabalho: acorda cansado(a) e não rende mais como antes.", "Exhaustion with work: wakes up tired and no longer performs as before.", "Agotamiento con el trabajo: se despierta cansado(a) y ya no rinde como antes."), L("Diz que 'não aguenta mais' o emprego, mas não consegue sair.", "Says they 'cannot take' the job anymore, but cannot leave either.", "Dice que 'ya no aguanta' el empleo, pero tampoco consigue salir.")],
      history: [L("A carga no trabalho dobrou nos últimos meses. Dorme mal em noite de véspera e melhora um pouco nas férias.", "The workload doubled in recent months. Sleeps badly the night before and improves a little on holidays.", "La carga de trabajo se duplicó en los últimos meses. Duerme mal la víspera y mejora un poco en vacaciones."), L("Trocou de chefia e passou a levar serviço para casa. A família reclama da ausência.", "Got a new manager and started taking work home. The family complains about the absence.", "Cambió de jefatura y empezó a llevar trabajo a casa. La familia se queja de la ausencia.")],
      steps: [L("'Eu gostava do que eu faço. Agora domingo à tarde já me dá um aperto no peito.'", "'I used to like what I do. Now Sunday afternoon already gives me a tightness in the chest.'", "'Me gustaba lo que hago. Ahora el domingo por la tarde ya me da una opresión en el pecho.'"), L("'Na folga eu até melhoro. Aí volto na segunda e some tudo de novo.' (dá um riso curto) 'Deve ser frescura.'", "'On a day off I even get better. Then I go back on Monday and it all disappears again.' (short laugh) 'It must be me being soft.'", "'En el día libre hasta mejoro. Después vuelvo el lunes y todo desaparece de nuevo.' (risa corta) 'Debe ser tontería mía.'"), L("'Eu contei as horas, como a senhora pediu. Onze horas na terça. E eu levei serviço pra casa mesmo assim.'", "'I counted the hours, like you asked. Eleven on Tuesday. And I still took work home.'", "'Conté las horas, como pidió. Once el martes. Y aun así llevé trabajo a casa.'"), L("'Minha filha me perguntou por que eu não rio mais.' (pausa) 'Eu não soube o que responder.'", "'My daughter asked me why I do not laugh anymore.' (pause) 'I did not know what to answer.'", "'Mi hija me preguntó por qué ya no me río.' (pausa) 'No supe qué responder.'")],
      note: L("Exaustão ligada ao trabalho, com melhora na folga.", "Work-related exhaustion, improving on days off.", "Agotamiento ligado al trabajo, con mejoría en el descanso."),
      find: { humor: [L("Humor cai nos dias de trabalho e levanta na folga — a variação acompanha a rotina, não o dia.", "Mood drops on working days and lifts on days off — the variation follows the routine, not the day.", "El ánimo baja los días de trabajo y sube en el descanso — la variación sigue la rutina, no el día."), L("Eu fico bem no sábado. Domingo à noite começa de novo.", "I am fine on Saturday. Sunday night it starts again.", "Estoy bien el sábado. El domingo por la noche empieza de nuevo."), { adaptacao: 3, tdm: -2, distimia: -1, insonia: 0 }],
        sono: [L("Dorme mal na véspera de dia útil; dorme bem no fim de semana.", "Sleeps badly the night before a working day; sleeps well at the weekend.", "Duerme mal la víspera de un día laboral; duerme bien el fin de semana."), L("Eu deito pensando na caixa de e-mail. No sábado eu apago.", "I lie down thinking about the inbox. On Saturday I am out cold.", "Me acuesto pensando en el correo. El sábado caigo redondo."), { adaptacao: 2, insonia: 1, tdm: 0 }],
        func: [L("Rendimento caiu e o erro aparece nas tarefas simples; a carga dobrou há seis meses.", "Performance dropped and errors show up in simple tasks; the workload doubled six months ago.", "El rendimiento cayó y el error aparece en tareas simples; la carga se duplicó hace seis meses."), L("Eu conferia tudo três vezes. Agora eu erro coisa boba e me odeio por isso.", "I used to check everything three times. Now I make silly mistakes and hate myself for it.", "Revisaba todo tres veces. Ahora cometo errores tontos y me odio por eso."), { adaptacao: 3, tdm: 1, distimia: 1 }],
        inicio: [L("Começou até seis meses depois da mudança na chefia — e não antes dela.", "Began within six months of the change in management — and not before it.", "Empezó hasta seis meses después del cambio de jefatura — y no antes."), L("Antes disso eu tava bem. Foi depois que mudou lá.", "Before that I was fine. It was after things changed there.", "Antes de eso estaba bien. Fue después de que cambió aquello."), { adaptacao: 3, distimia: -2, tdm: -1 }],
        social: [L("Mantém os vínculos, mas cancela por cansaço; não há perda de interesse pelas pessoas.", "Keeps relationships, but cancels out of tiredness; there is no loss of interest in people.", "Mantiene los vínculos, pero cancela por cansancio; no hay pérdida de interés por las personas."), L("Eu quero ver meus amigos. Só não tenho perna no fim do dia.", "I want to see my friends. I just have no legs left at the end of the day.", "Quiero ver a mis amigos. Solo que no me quedan piernas al final del día."), { adaptacao: 2, tdm: -2 }],
        corpo: [L("Dor de cabeça e no pescoço nos dias de reunião; exames sem alteração.", "Headache and neck pain on meeting days; tests show nothing.", "Dolor de cabeza y de cuello los días de reunión; los exámenes no muestran nada."), L("Meu pescoço trava. Fiz exame, não deu nada.", "My neck locks up. I had tests, nothing came up.", "Se me traba el cuello. Me hice exámenes, no salió nada."), { adaptacao: 2, insonia: 0 }] },
      form: { predisposing: L("Exigência alta consigo mesmo(a) e identidade muito colada ao trabalho.", "High self-demand and an identity tightly glued to work.", "Alta autoexigencia e identidad muy pegada al trabajo."), precipitating: L("A mudança de chefia e a carga que dobrou.", "The change in management and the workload that doubled.", "El cambio de jefatura y la carga que se duplicó."), perpetuating: L("Levar serviço para casa, não tirar folga e chamar o próprio limite de frescura.", "Taking work home, never taking time off, and calling one's own limit softness.", "Llevar trabajo a casa, no descansar y llamar tontería al propio límite."), protective: L("Vínculos preservados, humor que levanta na folga e consciência de que algo mudou.", "Preserved relationships, mood that lifts on days off, and awareness that something changed.", "Vínculos preservados, ánimo que sube en el descanso y conciencia de que algo cambió.") },
      why: L("O quadro começa depois de um estressor identificável (a mudança no trabalho), é desproporcional à exigência e melhora quando o estressor afrouxa — é transtorno de adaptação. Não é depressão maior porque o humor levanta na folga e o interesse pelas pessoas está preservado; não é distimia porque não são dois anos de humor baixo; não é insônia primária porque o sono acompanha os dias úteis, e não existe sozinho.", "The picture starts after an identifiable stressor (the change at work), is out of proportion to the demand, and improves when the stressor eases — this is adjustment disorder. It is not major depression because mood lifts on days off and interest in people is preserved; it is not dysthymia because there are not two years of low mood; it is not primary insomnia because sleep follows working days and does not stand alone.", "El cuadro empieza tras un estresor identificable (el cambio en el trabajo), es desproporcionado a la exigencia y mejora cuando el estresor afloja — es trastorno de adaptación. No es depresión mayor porque el ánimo sube en el descanso y el interés por las personas está preservado; no es distimia porque no son dos años de ánimo bajo; no es insomnio primario porque el sueño sigue los días laborales y no existe solo."),
      voice: { pre: [L("(esfrega os olhos)", "(rubs their eyes)", "(se frota los ojos)"), L("Olha...", "Look...", "Mira...")], post: L("Desculpa, eu falo disso e já fico assim.", "Sorry, I talk about this and I get like this.", "Perdón, hablo de esto y ya me pongo así."), ref: [L("Essa semana eu levei serviço pra casa de novo.", "This week I took work home again.", "Esta semana volví a llevar trabajo a casa."), L("Consegui não abrir o e-mail no domingo. Foi estranho e foi bom.", "I managed not to open my email on Sunday. It was strange and it was good.", "Logré no abrir el correo el domingo. Fue raro y fue bueno.")] } }
  };

  // A REPUTAÇÃO DA CLÍNICA ABRE PERFIS (7.5). Antes, os cinco arquétipos entravam em rodízio desde o
  // primeiro dia e a reputação não mudava NADA na porta de entrada. Agora a clínica começa com os
  // quadros mais diretos e passa a receber o que é mais difícil à medida que ganha nome — que é como
  // encaminhamento funciona de verdade: o serviço manda para quem já deu conta antes.
  const ARCHS = Object.keys(A);
  const EXIGE_REP = { panico: 10, tdah: 20, esgotamento: 35 };
  function perfisAbertos() {
    const r = typeof Wheel !== "undefined" ? Math.max(0, Wheel.rep().clinica) : 0;
    const abertos = ARCHS.filter((a) => r >= (EXIGE_REP[a] || 0));
    return abertos.length ? abertos : ARCHS.slice(0, 1);
  }
  const perfilTrancado = () => ARCHS.filter((a) => !perfisAbertos().includes(a)).map((a) => ({ id: a, em: EXIGE_REP[a] }));
  const FROM = [L("a escola", "the school", "la escuela"), L("o posto de saúde", "the health clinic", "el centro de salud"), L("o CAPS", "the CAPS", "el CAPS"), L("um colega psiquiatra", "a psychiatrist colleague", "un colega psiquiatra"), L("a assistência social", "social services", "la asistencia social")];

  // ---------------------------------------------------------------- criação de um caso a partir da semente
  const idOf = (n) => `gen:${n}`;
  function build(id, sd) {
    const arch = A[sd.a], r = rng(sd.s), gender = r() < 0.5 ? "f" : "m";
    const name = `${NAMES[gender][Math.floor(r() * 20)]} ${SURN[Math.floor(r() * 20)]}`, age = arch.age[0] + Math.floor(r() * (arch.age[1] - arch.age[0]));
    const look = { skin: SKINS_[Math.floor(r() * 8)], hairStyle: STY[gender][Math.floor(r() * STY[gender].length)], hairColor: HAIRC[Math.floor(r() * 6)], top: TOPS[Math.floor(r() * TOPS.length)], acc: "none" };
    const complaint = pick(arch.complaint[Math.floor(r() * 2)]), history = pick(arch.history[Math.floor(r() * 2)]);
    // retrato "ao molde da Maria" pré-desenhado (tools/python/desenhar-personagens.py pool 24): a semente escolhe
    // sempre o mesmo dos 24, sem consumir r() (a ordem dos outros sorteios do caso não pode mudar)
    const img = `assets/gerados/gerado-${sd.s % 24}.png`, s = pick(arch.symptom);
    const ageTxt = I18N.pick(L(`${age} anos`, `${age} years old`, `${age} años`));
    const steps = arch.steps.map((tx, i) => ({ who: "patient", text: pick(tx), note: i === 0 ? pick(arch.note) : null, mods: {}, options: Object.fromEntries(Object.keys(INTAKE[i]).map((ap) => [ap, fill(pick(INTAKE[i][ap]), { s })])) }));
    const c = { name, age: ageTxt, complaint, history, image: img, parent: null, dot: "dot-green", group: arch.group, type: I18N.pick(L("1ª Sessão: Anamnese", "1st session: intake interview", "1.ª sesión: anamnesis")), info: I18N.pick(L("Paciente novo (caso gerado): " + complaint, "New patient (generated case): " + complaint, "Paciente nuevo (caso generado): " + complaint)),
      message: { from: name, text: I18N.pick(L(`Olá, doutora. Sou ${name}. ${complaint} Podemos marcar? — ${name}`, `Hello, doctor. I'm ${name}. ${complaint} Can we schedule? — ${name}`, `Hola, doctora. Soy ${name}. ${complaint} ¿Podemos agendar? — ${name}`)) },
      fit: arch.fit, why: {}, steps, diagnosis: { answer: arch.answer, options: arch.options.slice(), why: pick(arch.why) }, gen: true, look, kid: false,
      voice: { intro: pick(L("(cumprimenta e senta) 'Oi, eu sou " + name + ", " + age + " anos.' ", "(greets and sits) 'Hi, I am " + name + ", " + age + ".' ", "(saluda y se sienta) 'Hola, soy " + name + ", " + age + " años.' ")), pre: arch.voice.pre.map(pick), post: pick(arch.voice.post), ref: arch.voice.ref.map(pick), hookA: pick(arch.voice.hookA), hookB: pick(arch.voice.hookB) } };
    const findings = Object.entries(arch.find).map(([d, [text, say, pts]]) => ({ d, text: pick(text), say: pick(say), pts }));
    const testes = {};
    BATS.forEach((b) => { const z0 = (PROF[arch.answer] || {})[b] || 0; testes[b] = { z: Math.round((z0 + (r() - 0.5) * 0.5) * 100) / 100, prof: Object.fromEntries(arch.options.map((o) => [o, (PROF[o] || {})[b] || 0])) }; });
    const form = Object.fromEntries(Object.entries(arch.form).map(([k, v]) => [k, pick(v)]));
    c.look = look;
    return { c, dx: { findings, form, testes } };
  }
  // cria (ou recria) todos os casos gerados no idioma atual
  function restore() {
    const g = st();
    Object.keys(g.seeds).forEach((id) => {
      const { c, dx } = build(id, g.seeds[id]);
      CASES[id] = c;
      if (window.DX_DATA) { DX_DATA.cases[id] = dx; if (typeof Dx !== "undefined" && Dx.resetData) Dx.resetData(); }
    });
  }
  function make(cycle, extra) {
    const g = st(); g.seq += 1;
    const id = idOf(g.seq), s = hash(`${id}:${cycle}:${g.seq}:${extra || ""}`) ^ (g.seq * 2654435761);
    const abertos = perfisAbertos();
    g.seeds[id] = { a: abertos[(g.seq + cycle) % abertos.length], s: s >>> 0, n: g.seq };
    const { c, dx } = build(id, g.seeds[id]); CASES[id] = c;
    if (window.DX_DATA) { DX_DATA.cases[id] = dx; if (typeof Dx !== "undefined" && Dx.resetData) Dx.resetData(); }
    return id;
  }

  // ---------------------------------------------------------------- turmas por ciclo e encaminhamentos
  const turmaSize = () => Math.min(10, 6 + Math.floor(Math.max(0, Wheel.rep().clinica) / 10));
  function turma(cycle, w) {
    const g = st();
    if (!g.cycles[cycle]) { g.cycles[cycle] = []; for (let i = 0; i < turmaSize(); i++) g.cycles[cycle].push(make(cycle, i)); saveState(); }
    const list = g.cycles[cycle].filter((id) => g.seeds[id] && CASES[id]), half = Math.ceil(list.length / 2);
    return w <= 2 ? list.slice(0, half) : list.slice(half);
  }
  const chance = () => Math.min(0.6, 0.10 + 0.05 * Wheel.level("multi") + 0.02 * (Math.max(0, Wheel.rep().clinica) / 10) + (typeof Career !== "undefined" ? Career.refBonus() : 0));
  // um encaminhamento novo chega pelo celular (aceitar cria a agenda dos próximos 2 semanas)
  function refer(source) {
    const g = st(), id = make(0, source || "ref"), from = FROM[(g.seq + week()) % FROM.length];
    state.inbox = state.inbox || [];
    state.inbox.push({ caseId: id, kind: "referral", status: "new", week: week(), from: pick(from) });
    g.refs.push({ id, week: week(), status: "new" });
    saveState();
    return id;
  }
  function weekRoll() {   // sorteio semanal (determinístico) só no modo contínuo
    if (!state.sandbox) return null;
    const g = st(), roll = ((week() * 37 + g.seq * 11) % 100) / 100;
    return roll < chance() ? refer("semana") : null;
  }
  function accept(id, yes) {
    const g = st(), ref = g.refs.find((x) => x.id === id);
    if (ref) { ref.status = yes ? "accepted" : "declined"; if (yes) ref.start = week() + 1; }
    if (yes) { state.xp += 3; Wheel.gain("multi", 1); }
    saveState();
  }
  // sessões dos encaminhamentos aceitos (2 semanas: consultas 1–2 e 3–4), para FU.plan
  function slots(w) {
    const out = [];
    st().refs.filter((x) => x.status === "accepted" && CASES[x.id] && !((state.pat || {})[x.id] || {}).closed).forEach((x, i) => {
      if (w === x.start) { out.push({ day: i % 3, caseId: x.id, sess: 1 }); out.push({ day: (i % 3) + 2, caseId: x.id, sess: 2 }); }
      if (w === x.start + 1) { out.push({ day: i % 3, caseId: x.id, sess: 3 }); out.push({ day: (i % 3) + 2, caseId: x.id, sess: 4 }); }
    });
    return out;
  }
  const referralText = (m) => { const c = CASES[m.caseId]; return c ? I18N.pick(L(`Encaminhamento de ${m.from}: ${c.name}, ${c.age}. ${c.complaint}`, `Referral from ${m.from}: ${c.name}, ${c.age}. ${c.complaint}`, `Derivación de ${m.from}: ${c.name}, ${c.age}. ${c.complaint}`)) : ""; };

  return { ARCHS, EXIGE_REP, perfisAbertos, perfilTrancado, make, restore, turma, refer, weekRoll, accept, slots, chance, referralText, st, build, INTAKE };
})();
window.Gen = Gen;
