"use strict";

// ===========================================================================
// Dados do aquário: espécies (com raridade, habitat, tamanho, temperamento e a forma de desenhar), tanques, decoração e
// equipamentos. Só dados: a lógica está em aquarium.js e o desenho em aquarium-art.js (2D) e scene3d.js (tanque 3D).
//   shape:  fish (comum) | round (baiacu) | tall (peixe-anjo) | long (moreia/enguia) | flat (raia) | jelly | turtle | octo | squid
//           crab | star | urchin | seahorse | shark | sponge | lobster | shrimp | nautilus | dragon | angler | sunfish
// ===========================================================================
window.AQ_DATA = (function () {
  const L = window.L;
  // id, forma, cores [corpo, detalhe, barbatana], raridade, habitat, tamanho (vagas), temperamento, origem, nome, curiosidade
  const S = (id, shape, cols, rarity, habitat, size, temper, from, name, about, extra) => Object.assign({ id, shape, cols, rarity, habitat, size, temper, from, name, about }, extra || {});
  const SPECIES = [
    // ---- já vêm com o aquário
    S("palhaco", "fish", ["#f2884a", "#ffffff", "#f2884a"], "comum", "recife", 1, "curioso", "base", L("Peixe-palhaço", "Clownfish", "Pez payaso"), L("Vive entre anêmonas e protege a casa dele com muita coragem. Todo peixe-palhaço nasce macho: o maior do grupo vira fêmea.", "Lives among anemones and bravely guards its home. Every clownfish is born male: the biggest of the group becomes female.", "Vive entre anémonas y protege su casa con mucho valor. Todos los peces payaso nacen machos: el mayor del grupo se vuelve hembra."), { stripe: "#ffffff" }),
    S("azul", "tall", ["#2f6bd8", "#15131f", "#f2c230"], "comum", "recife", 1, "ativo", "base", L("Peixe-cirurgião azul", "Blue tang", "Pez cirujano azul"), L("Nada em cardume e tem um espinho afiado na cauda, como um bisturi.", "Swims in schools and has a sharp spine on its tail, like a scalpel.", "Nada en cardumen y tiene una espina afilada en la cola, como un bisturí.")),
    S("baiacu", "round", ["#e8d27a", "#8a6a2a", "#e8d27a"], "comum", "recife", 1, "tímido", "base", L("Baiacu", "Pufferfish", "Pez globo"), L("Quando se assusta, incha como um balão para se defender.", "When scared, it puffs up like a balloon to defend itself.", "Cuando se asusta, se infla como un globo para defenderse.")),
    // ---- moradores da fenda (presentes)
    S("esponja", "sponge", ["#4fb8b0", "#1f6a6a", "#4fb8b0"], "raro", "fenda", 1, "calmo", "gift", L("Esponja-do-mar", "Sea sponge", "Esponja de mar"), L("Um dos animais mais antigos da Terra: filtra a água o dia inteiro. (Presente do João Esponja)", "One of the oldest animals on Earth: it filters water all day. (A gift from Porina)", "Uno de los animales más antiguos de la Tierra: filtra agua todo el día. (Regalo de João Esponja)"), { filter: 3 }),
    S("estrela", "star", ["#f2708a", "#ffd0dc", "#f2708a"], "raro", "fenda", 1, "calmo", "gift", L("Estrela-do-mar", "Starfish", "Estrella de mar"), L("Pode regenerar um braço perdido. (Presente do Patrício Estrela)", "Can regrow a lost arm. (A gift from Astéria)", "Puede regenerar un brazo perdido. (Regalo de Patrício Estrela)")),
    S("lula", "squid", ["#b08ae8", "#ff8fb8", "#8a6ad8"], "raro", "fenda", 2, "curioso", "gift", L("Lula", "Squid", "Calamar"), L("Tem três corações e muda de cor para se comunicar. (Presente do Murilo Lula)", "Has three hearts and changes color to communicate. (A gift from Tintinha)", "Tiene tres corazones y cambia de color para comunicarse. (Regalo de Murilo Lula)")),
    // ---- pesca no recife da praia / fenda (comuns e raros)
    S("anjo", "tall", ["#ffd84a", "#2f6bd8", "#2f6bd8"], "comum", "recife", 1, "curioso", "pesca", L("Peixe-anjo", "Angelfish", "Pez ángel"), L("Tem o corpo fino e alto como um disco e nada devagar entre os corais.", "Its body is thin and tall like a disc and it swims slowly among corals.", "Su cuerpo es fino y alto como un disco y nada despacio entre los corales.")),
    S("borboleta", "tall", ["#fff2a8", "#15131f", "#ffd84a"], "comum", "recife", 1, "tímido", "pesca", L("Peixe-borboleta", "Butterflyfish", "Pez mariposa"), L("Tem uma falsa mancha de olho perto da cauda para confundir predadores.", "It has a fake eyespot near the tail to confuse predators.", "Tiene un falso ojo cerca de la cola para confundir a los depredadores.")),
    S("donzela", "fish", ["#3a8ff0", "#8fd0ff", "#3a8ff0"], "comum", "recife", 1, "ativo", "pesca", L("Donzela-azul", "Blue damselfish", "Damisela azul"), L("Pequena e brilhante, cuida de um cantinho do recife como se fosse um jardim.", "Small and shiny, it tends a corner of the reef like a garden.", "Pequeña y brillante, cuida un rincón del arrecife como si fuera un jardín.")),
    S("papagaio", "fish", ["#3fb8a0", "#ff8fb8", "#3fb8a0"], "comum", "recife", 2, "ativo", "pesca", L("Peixe-papagaio", "Parrotfish", "Pez loro"), L("Tem dentes em forma de bico e, ao mastigar coral, produz areia branca.", "Has beak-shaped teeth and, by chewing coral, produces white sand.", "Tiene dientes en forma de pico y, al masticar coral, produce arena blanca.")),
    S("mandarim", "fish", ["#2f9bd8", "#ff8a3a", "#2fd8b8"], "raro", "recife", 1, "tímido", "pesca", L("Peixe-mandarim", "Mandarinfish", "Pez mandarín"), L("Um dos peixes mais coloridos do mundo, cheio de ondas azuis e laranja.", "One of the most colorful fish in the world, full of blue and orange waves.", "Uno de los peces más coloridos del mundo, lleno de ondas azules y naranjas."), { stripe: "#ff8a3a" }),
    S("cavalo", "seahorse", ["#f0b040", "#c87a20", "#f0b040"], "raro", "recife", 1, "calmo", "pesca", L("Cavalo-marinho", "Seahorse", "Caballito de mar"), L("É o pai que carrega os filhotes na barriga! Nada em pé.", "It's the dad who carries the babies in his belly! Swims upright.", "¡Es el papá quien lleva las crías en la barriga! Nada de pie.")),
    S("leao", "fish", ["#c8452a", "#ffffff", "#e8c8a0"], "raro", "recife", 2, "ativo", "pesca", L("Peixe-leão", "Lionfish", "Pez león"), L("Cheio de espinhos venenosos que parecem uma juba. Lindo, mas de longe!", "Full of venomous spines like a mane. Beautiful, but from a distance!", "Lleno de espinas venenosas como una melena. ¡Precioso, pero de lejos!"), { stripe: "#ffffff" }),
    S("moreia", "long", ["#7a8a3a", "#d8d070", "#7a8a3a"], "raro", "recife", 2, "tímido", "pesca", L("Moreia", "Moray eel", "Morena"), L("Vive escondida numa toca e tem uma segunda mandíbula dentro da garganta.", "Lives hidden in a burrow and has a second jaw inside its throat.", "Vive escondida en una cueva y tiene una segunda mandíbula dentro de la garganta.")),
    S("camarao", "shrimp", ["#ff7a5a", "#ffffff", "#ff7a5a"], "comum", "recife", 1, "ativo", "pesca", L("Camarão-limpador", "Cleaner shrimp", "Camarón limpiador"), L("Faz uma \"barbearia\": limpa parasitas de outros peixes, que fazem fila!", "Runs a \"barbershop\": cleans parasites off other fish, which line up!", "Hace de \"barbero\": limpia parásitos de otros peces, ¡que hacen fila!")),
    S("caranguejo", "crab", ["#e2573a", "#ffd0b8", "#e2573a"], "comum", "costa", 1, "ativo", "pesca", L("Caranguejo", "Crab", "Cangrejo"), L("Anda de lado e troca de carapaça ao crescer.", "Walks sideways and swaps its shell as it grows.", "Camina de lado y cambia de caparazón al crecer.")),
    S("eremita", "crab", ["#c8a878", "#f2884a", "#c8a878"], "comum", "costa", 1, "tímido", "pesca", L("Caranguejo-eremita", "Hermit crab", "Cangrejo ermitaño"), L("Não tem carapaça própria: muda de concha conforme cresce.", "It has no shell of its own: it changes shells as it grows.", "No tiene caparazón propio: cambia de concha a medida que crece."), { shell: true }),
    S("ourico", "urchin", ["#3a2f5a", "#8a7ac8", "#3a2f5a"], "comum", "costa", 1, "calmo", "pesca", L("Ouriço-do-mar", "Sea urchin", "Erizo de mar"), L("Cheio de espinhos, come algas e cobre-se com conchinhas para se disfarçar.", "Covered in spines, it eats algae and disguises itself with tiny shells.", "Cubierto de espinas, come algas y se disfraza con conchitas.")),
    S("lagosta", "lobster", ["#c8452a", "#ffd0b8", "#c8452a"], "raro", "costa", 2, "ativo", "pesca", L("Lagosta", "Lobster", "Langosta"), L("Tem o gosto na pata: sente sabores com as perninhas. Cresce a vida inteira.", "Tastes with its legs. It keeps growing its whole life.", "Saborea con las patas. Sigue creciendo toda la vida.")),
    S("tartaruga", "turtle", ["#5aa070", "#3f7a52", "#5aa070"], "raro", "aberto", 3, "calmo", "pesca", L("Tartaruga-marinha", "Sea turtle", "Tortuga marina"), L("Volta à praia onde nasceu para pôr os ovos.", "Returns to the beach where it was born to lay eggs.", "Vuelve a la playa donde nació para poner sus huevos.")),
    S("tubarao", "shark", ["#7a93b0", "#e7eef5", "#7a93b0"], "raro", "aberto", 3, "ativo", "pesca", L("Tubarãozinho", "Baby shark", "Tiburoncito"), L("Tem esqueleto de cartilagem, sem nenhum osso.", "Has a cartilage skeleton, with no bones at all.", "Tiene un esqueleto de cartílago, sin ningún hueso.")),
    S("polvo", "octo", ["#e8574a", "#ffb0a0", "#e8574a"], "raro", "costa", 2, "curioso", "pesca", L("Polvo", "Octopus", "Pulpo"), L("Muito inteligente: abre potes e passa por qualquer fresta.", "Very smart: opens jars and squeezes through any gap.", "Muy inteligente: abre frascos y pasa por cualquier rendija.")),
    S("raia", "flat", ["#c8a878", "#8a6a3a", "#c8a878"], "raro", "aberto", 3, "calmo", "pesca", L("Raia-pintada", "Spotted ray", "Raya manchada"), L("Parente dos tubarões, \"voa\" debaixo d'água batendo as barbatanas.", "A shark relative, it \"flies\" underwater flapping its fins.", "Pariente de los tiburones, \"vuela\" bajo el agua batiendo las aletas."), { spots: "#ffffff" }),
    S("agua-viva", "jelly", ["#f28ad4", "#ffffff", "#f28ad4"], "comum", "fenda", 1, "calmo", "pesca", L("Água-viva", "Jellyfish", "Medusa"), L("Não tem cérebro, coração nem ossos: é quase só água. Pulsa para se mover.", "Has no brain, heart or bones: it is almost all water. It pulses to move.", "No tiene cerebro, corazón ni huesos: es casi solo agua. Pulsa para moverse.")),
    S("lua-viva", "jelly", ["#cfe8ff", "#ffffff", "#9fc8ff"], "raro", "fenda", 1, "calmo", "pesca", L("Água-viva-lua", "Moon jelly", "Medusa luna"), L("Transparente, com quatro anéis brilhantes no meio: são as suas gônadas.", "Transparent, with four glowing rings in the middle: those are its gonads.", "Transparente, con cuatro anillos brillantes en el centro: son sus gónadas."), { glow: true }),
    // ---- profundezas da fenda
    S("lanterna", "fish", ["#2a3a7a", "#7ad8ff", "#2a3a7a"], "raro", "profundo", 1, "tímido", "pesca", L("Peixe-lanterna", "Lanternfish", "Pez linterna"), L("Vive no escuro e tem pontinhos que acendem no corpo, como lanterninhas.", "Lives in the dark and has dots on its body that light up like little lanterns.", "Vive en la oscuridad y tiene puntos en el cuerpo que se encienden como linternitas."), { glow: true }),
    S("pescador", "angler", ["#3a2f5a", "#ffe08a", "#3a2f5a"], "epico", "profundo", 2, "tímido", "pesca", L("Tamboril-pescador", "Anglerfish", "Rape pescador"), L("Usa uma \"isca\" luminosa na testa para atrair a comida no escuro total.", "Uses a glowing \"lure\" on its forehead to attract food in total darkness.", "Usa un \"señuelo\" luminoso en la frente para atraer comida en la oscuridad total."), { glow: true }),
    S("nautilo", "nautilus", ["#f2e0c8", "#c8452a", "#f2e0c8"], "epico", "profundo", 2, "calmo", "pesca", L("Náutilo", "Nautilus", "Nautilo"), L("Um \"fóssil vivo\": quase não mudou em 500 milhões de anos. A concha é uma espiral perfeita.", "A \"living fossil\": barely changed in 500 million years. Its shell is a perfect spiral.", "Un \"fósil viviente\": casi no ha cambiado en 500 millones de años. Su concha es una espiral perfecta.")),
    S("lua", "sunfish", ["#a8b8c8", "#e7eef5", "#a8b8c8"], "epico", "aberto", 4, "calmo", "pesca", L("Peixe-lua", "Sunfish", "Pez luna"), L("O maior peixe ósseo do mundo: parece uma cabeça nadando. Toma banho de sol na superfície.", "The biggest bony fish in the world: it looks like a swimming head. It sunbathes at the surface.", "El pez óseo más grande del mundo: parece una cabeza nadando. Toma el sol en la superficie.")),
    S("manta", "flat", ["#2a3a5a", "#ffffff", "#2a3a5a"], "epico", "aberto", 4, "curioso", "pesca", L("Raia-manta", "Manta ray", "Manta raya"), L("Tem até 7 metros de ponta a ponta e é curiosa: gosta de conhecer mergulhadores.", "Up to 7 meters wide and curious: it likes meeting divers.", "Hasta 7 metros de punta a punta y es curiosa: le gusta conocer buceadores."), { spots: "#ffffff" }),
    S("dragao", "dragon", ["#c8b84a", "#4a8a3a", "#e8d870"], "lendario", "recife", 2, "calmo", "pesca", L("Dragão-marinho-folhoso", "Leafy sea dragon", "Dragón marino"), L("Parece um pedaço de alga flutuando: é um camuflador tão bom que quase ninguém vê.", "Looks like a floating piece of seaweed: such a good camouflage that almost no one sees it.", "Parece un trozo de alga flotando: es tan buen camuflaje que casi nadie lo ve.")),
    S("celacanto", "fish", ["#3a5a8a", "#8fc8ff", "#3a5a8a"], "lendario", "profundo", 3, "calmo", "pesca", L("Celacanto", "Coelacanth", "Celacanto"), L("Achavam que tinha sumido junto com os dinossauros, até um pescador achar um vivo em 1938.", "Thought to have vanished with the dinosaurs, until a fisherman found a live one in 1938.", "Se creía extinto junto con los dinosaurios, hasta que un pescador encontró uno vivo en 1938."), { glow: true }),
    S("tubarao-baleia", "shark", ["#4a6a8a", "#ffffff", "#4a6a8a"], "lendario", "aberto", 4, "calmo", "pesca", L("Tubarão-baleia (filhote)", "Whale shark (pup)", "Tiburón ballena (cría)"), L("O maior peixe do mundo, e só come plâncton. Cada um tem um padrão de pintas único, como impressões digitais.", "The biggest fish in the world, and it only eats plankton. Each has a unique spot pattern, like fingerprints.", "El pez más grande del mundo y solo come plancton. Cada uno tiene un patrón de manchas único, como huellas digitales."), { spots: "#ffffff" }),
    S("coelho-mar", "fish", ["#ffd0e8", "#ffffff", "#ffd0e8"], "raro", "costa", 1, "curioso", "pesca", L("Lesma-do-mar", "Sea slug", "Babosa de mar"), L("Colorida e sem concha, é um molusco que \"pinta\" o corpo com o que come.", "Colorful and shell-less, a mollusc that \"paints\" its body with what it eats.", "Colorida y sin concha, es un molusco que \"pinta\" el cuerpo con lo que come."), { stripe: "#b58af0" })
  ];
  const RARITY = { comum: { w: 60, name: L("Comum", "Common", "Común"), c: "#7ab8ff" }, raro: { w: 28, name: L("Raro", "Rare", "Raro"), c: "#b58af0" }, epico: { w: 9, name: L("Épico", "Epic", "Épico"), c: "#ff9a4a" }, lendario: { w: 3, name: L("Lendário", "Legendary", "Legendario"), c: "#ffd84a" } };
  const HABITAT = { recife: L("Recife de coral", "Coral reef", "Arrecife de coral"), costa: L("Costa rochosa", "Rocky shore", "Costa rocosa"), aberto: L("Mar aberto", "Open sea", "Mar abierto"), fenda: L("Fenda do Biquíni", "Bikini Rift", "Grieta del Bikini"), profundo: L("Águas profundas", "Deep water", "Aguas profundas") };
  // tanques: capacidade em "vagas" (cada espécie ocupa 1 a 4)
  const TANKS = [
    { lv: 1, cap: 6, w: 1.8, name: L("Aquário pequeno", "Small aquarium", "Acuario pequeño"), price: 0 },
    { lv: 2, cap: 12, w: 2.4, name: L("Aquário médio", "Medium aquarium", "Acuario mediano"), price: 180 },
    { lv: 3, cap: 20, w: 3.0, name: L("Aquário grande", "Large aquarium", "Acuario grande"), price: 420 },
    { lv: 4, cap: 32, w: 3.6, name: L("Oceanário", "Oceanarium", "Oceanario"), price: 900 }
  ];
  // decoração: cada peça muda o visual e a "saúde"/beleza do aquário
  const DECOR = [
    { id: "alga", price: 25, beauty: 3, name: L("Algas ondulantes", "Swaying kelp", "Algas ondulantes"), color: "#3fa85a" },
    { id: "coral", price: 60, beauty: 6, name: L("Recife de coral", "Coral reef", "Arrecife de coral"), color: "#f2708a" },
    { id: "pedras", price: 20, beauty: 2, name: L("Pedras e cavernas", "Rocks and caves", "Piedras y cuevas"), color: "#8a8f98" },
    { id: "castelo", price: 70, beauty: 5, name: L("Castelinho", "Little castle", "Castillito"), color: "#c9a878" },
    { id: "bau", price: 90, beauty: 5, name: L("Baú do tesouro", "Treasure chest", "Cofre del tesoro"), color: "#a8793a" },
    { id: "tronco", price: 35, beauty: 3, name: L("Tronco afundado", "Sunken log", "Tronco hundido"), color: "#7a5a3a" },
    { id: "anemona", price: 55, beauty: 5, name: L("Anêmonas", "Anemones", "Anémonas"), color: "#e070c0" },
    { id: "navio", price: 140, beauty: 9, name: L("Naufrágio em miniatura", "Miniature shipwreck", "Naufragio en miniatura"), color: "#6a4a2a" }
  ];
  // equipamentos: melhoram a qualidade da água (filtro), o conforto (aquecedor) ou o brilho (luz)
  const GEAR = [
    { id: "filtro", price: 80, water: 18, name: L("Filtro", "Filter", "Filtro"), about: L("Mantém a água limpa por mais tempo.", "Keeps the water clean for longer.", "Mantiene el agua limpia por más tiempo.") },
    { id: "aquecedor", price: 70, comfort: 12, name: L("Aquecedor", "Heater", "Calentador"), about: L("Deixa a água na temperatura certa para peixes tropicais.", "Keeps the water at the right temperature for tropical fish.", "Deja el agua a la temperatura adecuada para peces tropicales.") },
    { id: "luz", price: 60, beauty: 4, name: L("Luz de LED", "LED light", "Luz LED"), about: L("Acende o aquário e faz as cores brilharem.", "Lights the aquarium and makes the colors glow.", "Ilumina el acuario y hace brillar los colores.") },
    { id: "bolhas", price: 45, water: 6, beauty: 2, name: L("Bolhador", "Bubbler", "Burbujeador"), about: L("Coloca oxigênio na água e faz bolhinhas.", "Adds oxygen to the water and makes little bubbles.", "Pone oxígeno en el agua y hace burbujitas.") },
    { id: "alimentador", price: 110, care: true, name: L("Alimentador automático", "Auto feeder", "Alimentador automático"), about: L("Solta comida sozinho: o aquário não passa fome se você esquecer.", "Drops food by itself: the aquarium won't go hungry if you forget.", "Suelta comida solo: el acuario no pasa hambre si lo olvidas.") }
  ];
  return { SPECIES, RARITY, HABITAT, TANKS, DECOR, GEAR };
})();
